name: pythagoras_square_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  avatar_glow: ^3.0.1
  bottom_picker: ^2.9.0
  dart_openai: ^5.1.0
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_swipe_button: ^2.1.3
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/images/
